version: 2
jobs:
  build:
    docker:
      - image: cimg/node:17.9.0

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npx npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npx ng build --prod --build-optimizer --no-progress
      # - run: npx ng test => No Tests Available => Think About Cypress Tests for Production Release
      - run:
          command: |
            docker build -t istioaksregistry.azurecr.io/customer-portal-ui:latest .
      - run:
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASS istioaksregistry.azurecr.io
      - run:
          command: |
            docker push istioaksregistry.azurecr.io/customer-portal-ui:latest
